### ISSUE TITLE
Confusion about Fresh Rendering

### ISSUE THREAD

**Issue by howardbaik** [fhdsl/ottr#15]
@cansavvy 

In the `render-all.yml` GHA, this [line](https://github.com/fhdsl/ottr/blob/main/.github/workflows/render-all.yml#L53) and this [line](https://github.com/fhdsl/ottr/blob/main/.github/workflows/render-all.yml#L104) suggests that we want a fresh run of the render each time the GHA runs. However, when the GHA actually runs, we don't see every single qmd file being re-run and rendered to HTML. We only see the changed qmd rendered to HTML. I think this [git pull](https://github.com/fhdsl/ottr/blob/main/.github/workflows/render-all.yml#L79) is what's causing the GHA to pull the old HTML files,  which means we aren't getting a fresh output.

**Comment by cansavvy** [comment]
We probably need to include a step that removes the old html files. We need the git pull so that if other branches have been merged at a similar time those changes are still included.  

But if we just delete the old html files that should be sufficient. See where we take this strategy in other OTTR repos: https://github.com/jhudsl/OTTR_Template_Website/blob/7b5acadb04d595e8fec0113f26961dfa72327976/.github/workflows/render-site.yml#L55

**Comment by howardbaik** [comment]
Shouldn't these commands remove the old html files? 

- `run: rm -rf docs/*`
- `run: rm -rf docs/no_toc/*`

They remove everything inside the specified directories, including old HTML files.

**Comment by howardbaik** [comment]
@cansavvy 

I've tried a bunch of things to `render-all.yml` (https://github.com/fhdsl/ottr/blob/main/.github/workflows/render-all.yml) on the main branch, but none of them seem to click. So far, I've managed to get the version of the book with a TOC **freshly** rendered and pushed to `docs/`, but I can't get the non-TOC version to be pushed to this repo. 

Could you please take a look?
